### ISSUE TITLE
Method "filterBy" has already been defined as a prop.

### ISSUE THREAD

**Issue by t0n1zz** [freearhey/vue2-filters#53] opened 2018-09-29 05:20 UTC
Hello, i think there is some bug in using filterBy prop on the package... i am using it with vue-select and this error come out... is there any solution that the prop is not using that? so i can use it with vue-select?

**Comment by akhoury** [comment] 2018-09-29 10:12
duplicate of https://github.com/freearhey/vue2-filters/issues/52

**Closed** 2018-11-05 21:03 UTC
